### PR TITLE
Make HAML-Lint fail when RuboCop fails

### LINKED ISSUE #317: HAML-Lint exits successfully even if RuboCop fails
Hi, I find a strange behavior of the latest version of HAML-Lint.

Even if RuboCop fails, HAML-Lint exits with the status `0`.

For example, assume that you have `Gemfile` and `.rubocop.yml` files:

```ruby
# Gemfile
source "https://rubygems.org"

gem "haml_lint"
```

```yaml
# .rubocop.yml
require:
  - rubocop-performance
```

When running `bundle exec haml-lint`, the error log is output but `haml-lint` exits successfully:

```
$ bundle exec haml-lint
cannot load such file -- rubocop-performance

(...stack trace...)

1 file inspected, 0 lints detected

$ echo $?
0
```

I created a repository for reproduction. Please see:
https://github.com/ybiquitous/haml-lint-reproduction

I expect it user-friendly that HAML-Lint also fails when RuboCop fails, but what do you think?

### PR DESCRIPTION
**Pull request by ybiquitous**
Fix #317

### CODE REVIEW

File: lib/haml_lint/linter/rubocop.rb [hunk 1]
```diff
@@ -56,7 +56,12 @@ def find_lints(ruby, source_map)
     # @param file [String]
     # @return [Array<RuboCop::Cop::Offense>]
     def lint_file(rubocop, file)
-      rubocop.run(rubocop_flags << file)
+      status = rubocop.run(rubocop_flags << file)
+      unless [::RuboCop::CLI::STATUS_SUCCESS, ::RuboCop::CLI::STATUS_OFFENSES].include?(status)
+        raise HamlLint::Exceptions::ConfigurationError,
+              "RuboCop exited unsuccessfully with status #{status}." \
+              ' Check the stack trace to see if there was a misconfiguration.'
+      end
```
Comment (ybiquitous) [inline lib/haml_lint/linter/rubocop.rb]: https://github.com/rubocop-hq/rubocop/blob/cc7e221b0e4723a75b59c4bd725a5555a13068dd/lib/rubocop/cli.rb#L7-L10

We may be able to improve the error message if we are considering errors except for misconfiguration. 🤔

File: spec/haml_lint/linter/rubocop_spec.rb [hunk 2]
```diff
@@ -101,4 +102,47 @@
...
+
+    context 'when RuboCop exits with an unexpected status' do
+      let(:rubocop_cli_status) { 123 }
+
+      it {
+        expect { subject }.to raise_error(HamlLint::Exceptions::ConfigurationError,
+                                          /RuboCop exited unsuccessfully with status 123/)
+      }
+    end
+  end
```
Comment (ybiquitous) [inline spec/haml_lint/linter/rubocop_spec.rb]: I'm not confident in the spec fix. Welcome any reviews!

**Comment by ybiquitous** [comment]
Oh, CI builds fail now...

**Comment by ybiquitous** [comment]
When I rebased the master branch, CI passed! 🎉 

Could you please review this?

**Comment by ybiquitous** [comment]
Thanks for new release!
